### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e3-irma-m#1]
Los _checkboxes_ deben tener el mismo nombre, además faltó el atributo `value`

https://github.com/UniversidadCristobalColon/pw2-e3-irma-m/blob/f7b06e2e36908e25451d1395f123e53928465bbb/pw2-e5.html#L26

Faltó el atributo `name`
https://github.com/UniversidadCristobalColon/pw2-e3-irma-m/blob/f7b06e2e36908e25451d1395f123e53928465bbb/pw2-e5.html#L30

**Comment by irma-m** [comment]
[pw2-e3-irma-m-f7b06e2e36908e25451d1395f123e53928465bbb.zip](https://github.com/UniversidadCristobalColon/pw2-e3-irma-m/files/3665157/pw2-e3-irma-m-f7b06e2e36908e25451d1395f123e53928465bbb.zip)
